### ISSUE TITLE
Make the scripts MacOS and Linux compatible

### ISSUE THREAD

**Issue by supertobi** [gregzaal/HDR-Merge#1]
MacOS and Linux use "/" instead of "\" as path separator. For that reason you souldn't use hard coded separators, but the os.path class in your code.  

E.g.
https://github.com/gregzaal/HDR-Merge/blob/21873c1ab78253ab70ac3c0005efcba57f15ce06/blender/blender_merge.py#L53

This should not be necessary if you would use os.path.join[1] here:

https://github.com/gregzaal/HDR-Merge/blob/21873c1ab78253ab70ac3c0005efcba57f15ce06/blender/blender_merge.py#L58

[1] https://docs.python.org/3.5/library/os.path.html#os.path.join

**Comment by gregzaal** [comment]
But it already uses `/` as the separator, which works in windows too (with python). Hence the `OUT_FOLDER = OUT_FOLDER.replace('\\', '/')` line. In theory everything should work in linux/mac, I just haven't tested it.

You're right that os.path.join would be better.

**Comment by supertobi** [comment]
I would like to test it with Linux for you. Could you provide a step by step description with example images?
