### ISSUE TITLE
no jpgs

### ISSUE THREAD

**Issue by adamfilip** [gregzaal/HDR-Merge#3]
I was following your hdri tutorial. and, downloaded your examples Raw files.. exported EXRs but no jpgs were outputted

**Comment by gregzaal** [comment]
Are there any errors outputted to the console during the merging process?

Could be you're using a newer version of Luminance HDR - only version [2.4.0](https://sourceforge.net/projects/qtpfsgui/files/luminance/2.4.0/) will work.

**Comment by sybrenstuvel** [comment]
I have the same:

```
Fra:0 Mem:2183.17M (0.00M, Peak 2183.18M) | Time:00:28.98 | Compositing | Tile 507-512
Fra:0 Mem:2183.17M (0.00M, Peak 2183.18M) | Time:00:29.00 | Compositing | Tile 508-512
Fra:0 Mem:2183.17M (0.00M, Peak 2183.18M) | Time:00:29.01 | Compositing | Tile 509-512
Fra:0 Mem:2183.17M (0.00M, Peak 2183.18M) | Time:00:29.05 | Compositing | Tile 510-512
Fra:0 Mem:2183.17M (0.00M, Peak 2183.18M) | Time:00:29.22 | Compositing | Tile 511-512
Fra:0 Mem:2183.17M (0.00M, Peak 2183.18M) | Time:00:29.23 | Compositing | Tile 512-512
Fra:0 Mem:2183.17M (0.00M, Peak 2183.18M) | Time:00:29.23 | Compositing | De-initializing execution
Fra:0 Mem:2183.17M (0.00M, Peak 2183.18M) | Time:00:29.23 | Sce:  Ve:0 Fa:0 La:0
Progress: 0.0
Progress: 0.0
Saved: 'A:\photos\2018-zomer\2018-08 panos-zomer\01-brug-over-sava\tiff8\Merged\exr\merged_000.exr'
 Time: 00:32.57 (Saving: 00:03.33)

Info: Total files 7 | Changed 0 | Failed 0
Info: Total files 7 | Changed 7 | Failed 0

Blender quit
ERROR: the argument ('reinhard02') for option '--autoag' is invalid

Progress: 100.0
Done!!!
```

However, this was indeed caused by a too-new Luminance HDR. I had installed the latest version (2.5.x) and then thought I downgraded to 2.4.0. This wasn't true, though -- 2.4.0 installed to `C:\Program Files (x86)` and didn't remove the 2.5.x install in `C:\Program Files`. Uninstalling both, and making sure the paths were correct, fixed it all.
